version: '3'
services:
  employeedb:
    build: 
      context: .
      dockerfile: ./database/Dockerfile
    image: rogerbv9017/employeedb:latest
    container_name: ${DB_HOST}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - networkdev
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "employeedb", "-U", "admin"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  backend:
    image: rogerbv9017/employeebackend:latest
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      employeedb:
        condition: service_healthy
    command: bash -c "npx prisma migrate dev --name init && npm run seed && npm run start"
    volumes:
      - ./backend:/app/
    networks:
      - networkdev
  frontend:
    image: rogerbv9017/employeefrontend:latest
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:5173"
      - "5174:5174"
    depends_on:
      - backend
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
    networks:
      - networkdev
networks:
  networkdev: