apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17beta2
          env: 
            - name: POSTGRES_DB
              value: employeedb
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: "123456"
          ports:
            - containerPort: 5432